---
# tasks file for ansible-perlbrew/

- name: Install perlbrew deps from apt
  apt:
    name: ['bzip2',  'uuid-dev', 'libssl-dev', 'libz-dev', 'libnet-ssleay-perl']
    state: latest
  become: true

- name: install perl modules
  cpanm:
    name: "{{ item }}"
    version: "999.9"
  with_items: "{{ perlmodules }}"
  become: true

