---
# tasks file for ansible-role-perlbrew/

- name: Install perlbrew deps from apt
  apt:
    name: ['bzip2',  'uuid-dev', 'libssl-dev', 'libz-dev', 'libnet-ssleay-perl', 'libexpat1-dev']
    state: latest
  become: true

- name: install perl modules
  community.general.cpanm:
    name: "{{ item }}"
  with_items: "{{ perlmodules }}"
  become: true

